variables:
  GIT_SUBMODULE_STRATEGY: recursive
  ROLE: init

stages:
  - push_to_github
  - import_to_ansible_galaxy

push_to_github:
  stage: push_to_github
  script:
    - mkdir -p ~/tmp/$ROLE
    - pwd
    - rsync --exclude .gitlab-ci.yml --exclude local . ~/tmp/$ROLE
    - cd ~/tmp/$ROLE
    - git remote add github git@github.com:johnpion/ansible-role-$ROLE.git
    # - git pull github main
    # - git rm .gitlab-ci.yml
    # - git rm -r local
    - git add .
    - git commit -m "Automatic commit from GitLab"
    - git push github main
    - cd ~/tmp
    # - rm -rf ~/tmp/$ROL E
  only:
    - main

import_to_ansible_galaxy:
  stage: import_to_ansible_galaxy
  script:
    - ansible-galaxy role import johnpion ansible-role-$ROLE
  only:
    - main
