variables:
  GIT_SUBMODULE_STRATEGY: recursive
  ROLE: init

stages:
  - push_to_github
  - import_to_ansible_galaxy

push_to_github:
  stage: push_to_github
  script:
    - git clone --branch main git@github.com:johnpion/ansible-role-$ROLE.git github_repo
    - rsync -ar --exclude .gitlab-ci.yml --exclude local ./ github_repo/
    - cd github_repo
    - git remote set-url origin git@github.com:johnpion/ansible-role-$ROLE.git
    - git add .
    - COMMIT_MESSAGE=$(git log -1 --pretty=%B)
    - git commit -m "$COMMIT_MESSAGE"
    - git push origin main
  only:
    - main

import_to_ansible_galaxy:
  stage: import_to_ansible_galaxy
  script:
    - ansible-galaxy role import johnpion ansible-role-$ROLE
  only:
    - main
