variables:
  GIT_SUBMODULE_STRATEGY: recursive
  ROLE: init

stages:
  - push_to_github
  - import_to_ansible_galaxy

push_to_github:
  stage: push_to_github
  script:
    # - ls
    - rm -f '.gitlab-ci.yml'
    - rm -rf local
    - git add .
    - git commit -a -m "Automatic commit from GitLab"
    - git remote add github git@github.com:johnpion/ansible-role-$ROLE.git
    - git push github main
  only:
    - main

import_to_ansible_galaxy:
  stage: import_to_ansible_galaxy
  script:
    - ansible-galaxy role import johnpion ansible-role-$ROLE
  only:
    - main
