- name: Add to grub. Change new auto naming of ehternet devices to old behavior
  ansible.builtin.lineinfile:
    dest: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"'
  become: true
  notify: Reconfigure grub
  when:
    - ansible_default_ipv4.interface != 'eth0'
    - ansible_default_ipv4.interface is not search ("vmbr")
  register: grub_update

- name: Change default network name
  ansible.builtin.replace:
    backup: true
    path: /etc/network/interfaces
    regexp: "{{ ansible_default_ipv4 }}"
    replace: "eth0"
  become: true
  when:
    - ansible_default_ipv4.interface != 'eth0'
    - ansible_default_ipv4.interface is not search ("vmbr")

- name: Set hostname for non-proxmox nodes
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  when: ansible_virtualization_type != "lxc"

- name: Set ~/.bashrc
  ansible.builtin.copy:
    src: bashrc
    dest: /root/.bashrc
    owner: root
    group: root
    mode: "0640"
    backup: true
  when:
    - ansible_distribution == "Debian"

- name: Update sources.list
  ansible.builtin.template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    backup: true
    mode: "0644"
  when: apt_source

- name: Delete pve-enterprise repo from apt
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent
  when: '"proxmox" in group_names'

- name: Delete pbs-enterprise repo from apt
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/pbs-enterprise.list
    state: absent
  when: '"pbs" in group_names'

- name: Add soft for HP RAID
  ansible.builtin.import_tasks: hp.yml
  when: ansible_system_vendor == "HP"

- name: Upgrade system
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
    force: true
    update_cache: true
    upgrade: full
  tags: init_apt
  register: apt
  ignore_errors: true

### When new stable release of Debian is anonsed, apt update ask to press "yes"
- name: Fix apt-get
  ansible.builtin.command: apt-get update --allow-releaseinfo-change
  when: apt.failed
  register: fix_apt
  tags: skip_ansible_lint

- name: Upgrade system
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
    force: true
    update_cache: true
    upgrade: full
  tags: skip_ansible_lint
  when: fix_apt is changed

- name: Install software
  ansible.builtin.apt:
    pkg:
      - bridge-utils
      - parted
      - rsync
      - sudo
      - tmux
      - xz-utils
    autoclean: true
  tags: init_apt

- name: Gather the service facts
  ansible.builtin.service_facts:

- name: Disable rpcbind
  ansible.builtin.systemd:
    name: rpcbind
    state: stopped
    enabled: false
  when: "'rpcbind' in ansible_facts.services"

- name: Locale gen
  community.general.locale_gen:
    name: "{{ item }}"
  with_items:
    - "{{ locales }}"

- name: Set locale
  ansible.builtin.lineinfile:
    path: /etc/default/locale
    line: '{{ item }}="{{ default_locale }}"'
    regexp: "{{ item }}.*"
  with_items:
    - LANG
    - LC_ALL

- name: Journald
  ansible.builtin.template:
    src: journald.j2
    dest: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: "0644"
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_release == "buster"
    - ansible_virtualization_type == "lxc"
  notify: Restart journald

- name: "Set timezone {{ timezone }}"
  community.general.timezone:
    name: "{{ timezone }}"
  notify: Restart cron

- name: Logrotate
  ansible.builtin.copy:
    src: logrotate.service
    dest: /lib/systemd/system
    owner: root
    group: root
    mode: "0644"
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_release == "buster"
    - ansible_virtualization_type == "lxc"
  notify: Restart logrotate

- name: Config ssh
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"
  tags: init_ssh
  register: ssh_synchronized
  notify: Restart ssh

- name: Config network
  ansible.builtin.import_tasks: network.yml
  tags: network

- name: Config users
  ansible.builtin.import_tasks: user.yml
