# change new auto naming of ehternet devices to old behavior
- name: add to grub
  ansible.builtin.lineinfile:
    dest: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"'
  become: true
  notify: reconfigure grub
  when:
    - ansible_default_ipv4.interface != 'eth0'
    - ansible_default_ipv4.interface is not search ("vmbr")

- name: change default network name
  ansible.builtin.command: sed -i 's/{{ ansible_default_ipv4.interface }}/eth0/g' /etc/network/interfaces
  become: true
  when:
    - ansible_default_ipv4.interface != 'eth0'
    - ansible_default_ipv4.interface is not search ("vmbr")

# set hostname for non-proxmox nodes
- name: set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  when: ansible_virtualization_type != "lxc"

- name: set bashrc
  ansible.builtin.lineinfile:
    path: /root/.bashrc
    line: 'export PS1="\[\e]0;\u@\H: \w\a\]${debian_chroot:+($debian_chroot)}\[\e[1;31m\]\u\[\e[1;33m\]@\[\e[1;36m\]\H \[\e[1;33m\]\w \[\e[1;35m\]\$ \[\e[0m\]"'

- name: sources.list
  ansible.builtin.template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    backup: true
    mode: 0644
  when: apt_source

- name: delete pve-enterprise repo from apt
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent
  when: '"proxmox" in group_names'

- name: delete pbs-enterprise repo from apt
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/pbs-enterprise.list
    state: absent
  when: '"pbs" in group_names'

- name: upgrade system
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
    force: true
    update_cache: true
    upgrade: full
  tags: init_apt
  register: apt
  ignore_errors: true

### When new stable release of Debian is anonsed, apt update ask to press "yes"
- name: fix apt-get
  ansible.builtin.command: apt-get update --allow-releaseinfo-change
  when: apt.failed
  register: fix_apt
  tags: init_apt

- name: upgrade system
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
    force: true
    update_cache: true
    upgrade: full
  tags: init_apt
  when: fix_apt is changed

- name: install software
  ansible.builtin.apt:
    pkg:
      - rsync
      - sudo
      - tmux
    autoclean: true
  tags: init_apt

- name: Gather the service facts
  ansible.builtin.service_facts:

- name: disable rpcbind
  ansible.builtin.systemd:
    name: rpcbind
    state: stopped
    enabled: false
  when: "'rpcbind' in ansible_facts.services"

- name: locale gen
  ansible.builtin.locale_gen:
    name: "{{ item }}"
  with_items:
    - "{{ locales }}"

- name: set locale
  ansible.builtin.lineinfile:
    path: /etc/default/locale
    line: '{{ item }}="{{ default_locale }}"'
    regexp: "{{ item }}.*"
  with_items:
    - LANG
    - LC_ALL

- name: journald
  ansible.builtin.template:
    src: journald.j2
    dest: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: 0644
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_release == "buster"
    - ansible_virtualization_type == "lxc"
  notify:
    - restart journald

- name: "set timezone {{ timezone }}"
  timezone:
    name: "{{ timezone }}"
  notify: restart cron

- name: logrotate
  ansible.builtin.copy:
    src: logrotate.service
    dest: /lib/systemd/system
    owner: root
    group: root
    mode: 0644
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_release == "buster"
    - ansible_virtualization_type == "lxc"
  notify:
    - restart logrotate

- name: ssh config
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  tags: init_ssh
  register: ssh_synchronized
  notify: restart ssh

- include: network.yml
  tags: network

- include: user.yml
