- name: add addition interfaces
  lineinfile:
    path: /etc/network/interfaces
    line: "source /etc/network/interfaces.d/*"

- name: check local configs
  delegate_to: localhost
  stat:
    path: files/{{ inventory_hostname }}/network
  register: network_config_files

- name: update_network_interfaces
  synchronize:
    src: files/{{ inventory_hostname }}/network
    dest: /etc/
    recursive: yes
  when: network_config_files.stat.exists
  notify: chown network
