- name: create users
  user:
    name: "{{ user.name }}"
    groups: "{{ user.groups }}"
  when: user is defined

- name: set sudo
  lineinfile:
    path: /etc/sudoers
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"

- name: passwd root
  # shell: echo {{ passwd }} | echo {{ passwd }} | passwd
  user:
    user: root
    password: "{{ passwd|password_hash('sha512') }}"
  when: passwd is defined
  no_log: true
  tags: init_passwd
