- name: Restart logrotate
  ansible.builtin.systemd:
    name: logrotate
    state: restarted
    daemon_reload: true

- name: Restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
    daemon_reload: true

- name: Restart cron
  ansible.builtin.service:
    name: cron
    state: restarted

- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted
  # when: ssh_synchronized.changed

- name: Chown network
  ansible.builtin.command: find /etc/network -type f -exec chmod -x {} \;
  tags: skip_ansible_lint

- name: Reconfigure grub
  ansible.builtin.command: update-grub
  become: true
  tags: skip_ansible_lint
