- name: restart logrotate
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: logrotate

- name: restart cron
  ansible.builtin.systemd:
    state: restarted
    name: cron
